### PR TITLE
Update hardcoded strings to 'github.com/mindjiver'

### PR DESCRIPTION
**Pull request by mindjiver**
After moving the project to the schubergphilis organisation in Github
we update any references to the former maintainer.

### CODE REVIEW

**Comment by mindjiver** [comment]
There is a Travis CI configuration file but I guess you need to connect it to your Shuberg Philis account :smile: . Lets use this PR to validate that the build and tests get executed on PRs.

**Comment by miguelaferreira** [comment]
ping @svanharmelen

**Comment by mindjiver** [comment]
Also I guess you might want to migrate to using @svanharmelen Go-lang Cloudstack package. Even though my hack works it might be for makeing maintenance easier. For now I left all references to github.com/mindjiver/gopherstack

**Comment by svanharmelen** [comment]
Thanks! Will merge this one and do some testing to see everything turns green again...

**Pull request merged**
